apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: prometheus-server
  namespace: vela-system
spec:
  components:
    - type: k8s-objects
      name: prometheus-server-ns
      properties:
        objects:
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: o11y-system
  policies:
    - type: shared-resource
      name: shared-namespace
      properties:
        rules:
          - selector:
              resourceTypes: ["Namespace"]
    - type: topology
      name: topology-o11y
      properties:
        clusterLabelSelector: {}
        namespace: o11y-system
    - type: topology
      name: topology-local
      properties:
        clusters: ["local"]
        namespace: o11y-system
    - type: override
      name: component-ns
      properties:
        selector: ["prometheus-server-ns"]
    - type: override
      name: component-prometheus
      properties:
        selector: ["prometheus-config", "prometheus-server"]
    - type: override
      name: component-thanos
      properties:
        selector: ["thanos-query"]
  workflow:
    steps:
      - type: deploy
        name: deploy-ns
        properties:
          policies: ["component-ns", "topology-o11y"]
      - type: deploy
        name: deploy-prometheus
        properties:
          policies: ["component-prometheus", "topology-o11y"]
      - type: deploy
        name: deploy-thanos
        properties:
          policies: ["component-thanos", "topology-local"]