apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cloudshell
  namespace: vela-system
spec:
  components:
    - name: cloudshell-operator
      type: helm
      properties:
        repoType: helm
        url: https://release.daocloud.io/chartrepo/cloudshell
        chart: cloudtty
        version: 0.3.0
        values:
          image:
            registry: docker.io
            repository: oamdev/cloudshell-operator
            tag: "v0.3.0"
          jobTemplate:
            image:
              registry: docker.io
              repository: oamdev/cloudshell
              tag: "v1.7.2"
