apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: o11n-system:thanos-query
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: thanos-query
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: o11n-system:thanos-query
subjects:
  - kind: ServiceAccount
    name: thanos-query
    namespace: o11n-system