apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: o11n-system
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: thanos-query
spec:
  selector:
    matchLabels:      
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: thanos-query
  replicas: 1
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/instance: thanos-query
    spec:
      containers:
        - name: thanos
          image: quay.io/thanos/thanos:v0.8.0
          args:
            - query
            - --http-address=0.0.0.0:9090
            - --log.level=debug
            - --query.replica-label=replica
            - --store=dnssrv+prometheus-server:10901
          ports:
            - name: http
              containerPort: 9090
          livenessProbe:
            httpGet:
              port: http
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: http
              path: /-/ready
