apiVersion: v1
kind: Service
metadata:
  name: loki-memberlist
  namespace: o11n-system
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 7946
      targetPort: memberlist-port
      protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki