apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: o11n-system
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-server
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-server
