{
 "title": "Kubernetes APIServer",
 "description": "Latency and QPS for Kubernetes apiserver. ",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubernetes_build_info,cluster)"
    }
   },
   { "name": "rate_interval", "query": "3m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " Request QPS (by verb)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\"}[$rate_interval])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": " Request QPS (by resource)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\",resource!=\"\"}[$rate_interval])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Detail Request QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\"}[$rate_interval])) by (verb,resource)",
     "legendFormat": "{{verb}} - {{resource}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\",cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\",cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\",cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Average Latency (by verb)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb!~\"CONNECT|WATCH\",cluster=\"$cluster\"}[$rate_interval])) by (verb) / sum(rate(apiserver_request_duration_seconds_count{verb!~\"CONNECT|WATCH\",cluster=\"$cluster\"}[$rate_interval])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{verb!~\"CONNECT|WATCH\",cluster=\"$cluster\"}[$rate_interval])) by (verb,resource) / sum(rate(apiserver_request_duration_seconds_count{verb!~\"CONNECT|WATCH\",cluster=\"$cluster\"}[$rate_interval])) by (verb,resource)",
     "legendFormat": "{{verb}} {{resource}}"
    }
   ]
  },
  { "title": "WorkQueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Service Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "service time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"kubernetes-apiservers\",cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"kubernetes-apiservers\",cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"kubernetes-apiservers\",cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Process Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "processing time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket{job=\"kubernetes-apiservers\",cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(workqueue_work_duration_seconds_bucket{job=\"kubernetes-apiservers\",cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket{job=\"kubernetes-apiservers\",cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "processing time" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{cluster=\"$cluster\",job=\"kubernetes-apiservers\"})",
     "legendFormat": "QueueSize"
    }
   ]
  },
  {
   "title": "Retry Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "count/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{cluster=\"$cluster\",job=\"kubernetes-apiservers\"}[$rate_interval]))",
     "legendFormat": "Retries"
    }
   ]
  },
  { "title": "Watches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Number of Watches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_registered_watchers{cluster=\"$cluster\"}) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Watch Event Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_watch_events_sizes_bucket{cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(apiserver_watch_events_sizes_bucket{cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(apiserver_watch_events_sizes_bucket{cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Watch Event Rate (by resource)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_watch_events_total{cluster=\"$cluster\"}[$rate_interval])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Number of Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_object_counts{cluster=\"$cluster\"}) by (resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd request latency",
   "type": "graph",
   "description": "etcd request latency (p95)",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket{cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(etcd_request_duration_seconds_bucket{cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_request_duration_seconds_bucket{cluster=\"$cluster\"}[$rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Request Average Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_request_duration_seconds_sum{cluster=\"$cluster\"}[$rate_interval])) by (type) / sum(rate(etcd_request_duration_seconds_count{cluster=\"$cluster\"}[$rate_interval])) by (type)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "KubeVela System",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "query": "3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Computation Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Applications",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_phase_number{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "KubeVela Controller Resource Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=\"kubevela\"}) by (container)/ sum(container_spec_memory_limit_bytes{container=\"kubevela\"}) by (container)",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"kubevela\"}[2m])) by (container) / (sum(container_spec_cpu_quota{container=\"kubevela\"}/100000) by (container))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "ClusterGateway Resource Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=\"kubevela-vela-core-cluster-gateway\"}) by (container)/ sum(container_spec_memory_limit_bytes{container=\"kubevela-vela-core-cluster-gateway\"}) by (container)",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"kubevela-vela-core-cluster-gateway\"}[2m])) by (container) / (sum(container_spec_cpu_quota{container=\"kubevela-vela-core-cluster-gateway\"}/100000) by (container))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "core" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"kubevela\",cluster=\"local\"}[$rate_interval])) by (container)",
     "legendFormat": "KubeVela Controller"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"kubevela-vela-core-cluster-gateway\",cluster=\"local\"}[$rate_interval])) by (container)",
     "legendFormat": "Cluster Gateway"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"kubevela\",cluster=\"local\"})",
     "legendFormat": "KubeVela Controller WSS"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"kubevela-vela-core-cluster-gateway\",cluster=\"local\"})",
     "legendFormat": "Cluster Gateway WSS"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Controller Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum(workqueue_depth{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Controller Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "count/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "count/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (result, controller)",
     "legendFormat": "{{result}}: {{controller}}"
    }
   ]
  },
  {
   "title": "Average Reconcile Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (controller) / sum(rate(controller_runtime_reconcile_time_seconds_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "ApplicationController  Reconcile Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{controller=\"application\",cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) / sum(rate(controller_runtime_reconcile_time_seconds_count{controller=\"application\",cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"application\",cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"application\",cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "ApplicationController Reconcile Stage Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(create_app_handler_time_seconds_sum{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) / sum(rate(create_app_handler_time_seconds_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval]))",
     "legendFormat": "CreateAppHandler"
    },
    {
     "expr": "sum(rate(handle_finalizers_time_seconds_sum{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) / sum(rate(handle_finalizers_time_seconds_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval]))",
     "legendFormat": "HandleFinalizers"
    },
    {
     "expr": "sum(rate(parse_appFile_time_seconds_sum{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) / sum(rate(parse_appFile_time_seconds_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval]))",
     "legendFormat": "ParseAppFile"
    },
    {
     "expr": "sum(rate(prepare_current_appRevision_time_seconds_sum{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) / sum(rate(prepare_current_appRevision_time_seconds_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval]))",
     "legendFormat": "PrepareCurrentAppRevision"
    },
    {
     "expr": "sum(rate(apply_appRevision_time_seconds_sum{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) / sum(rate(apply_appRevision_time_seconds_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval]))",
     "legendFormat": "ApplyAppRevision"
    },
    {
     "expr": "sum(rate(apply_policies_sum{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) / sum(rate(apply_policies_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval]))",
     "legendFormat": "ApplyPolicies"
    },
    {
     "expr": "sum(rate(gc_resourceTrackers_time_seconds_sum{cluster=\"local\",app_kubernetes_io_name=\"vela-core\",stage=\"-\"}[$rate_interval])) / sum(rate(gc_resourceTrackers_time_seconds_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\",stage=\"-\"}[$rate_interval]))",
     "legendFormat": "GCResourceTrackers"
    }
   ]
  },
  {
   "title": "ApplicationController Client Request Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_request_time_seconds_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (Kind, verb)",
     "legendFormat": "{{verb}}: {{Kind}}"
    }
   ]
  },
  {
   "title": "ApplicationController  Client Request Average Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_request_time_seconds_sum{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (Kind, verb) / sum(rate(client_request_time_seconds_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (Kind, verb)",
     "legendFormat": "{{verb}}: {{Kind}}"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Number of Applications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(application_phase_number{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(application_phase_number{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}) by (phase)",
     "legendFormat": "Phase: {{phase}}"
    }
   ]
  },
  {
   "title": "Number of Steps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workflow_step_phase_number{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(workflow_step_phase_number{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}) by (step_type)",
     "legendFormat": "Type: {{step_type}}"
    }
   ]
  },
  {
   "title": "StepStatus Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workflow_step_phase_number{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}) by (phase)",
     "legendFormat": "Status: {{phase}}"
    },
    {
     "expr": "sum(workflow_step_phase_number{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}) by (step_type, phase)",
     "legendFormat": "{{step_type}}: {{phase}}"
    }
   ]
  },
  {
   "title": "Workflow Initialize Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workflow_initialized_num{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval]))",
     "legendFormat": "Initialize Rate"
    }
   ]
  },
  {
   "title": "Workflow Average Complete Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workflow_finished_time_seconds_sum{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (phase) / sum(rate(workflow_finished_time_seconds_count{cluster=\"local\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "X-Definitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "ComponentDefinitions",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.items[*].metadata.name", "name": "Name" },
        { "jsonPath": "$.items[*].metadata.namespace", "language": "jsonpath", "name": "Namespace" },
        {
         "jsonPath": "$.items[*].metadata.annotations.\"definition.oam.dev/description\"",
         "language": "jsonata",
         "name": "Description"
        },
        {
         "jsonPath": "$.items[*].metadata.($exists(annotations.\"custom.definition.oam.dev/alias.config.oam.dev\") ? annotations.\"custom.definition.oam.dev/alias.config.oam.dev\" : '')",
         "language": "jsonata",
         "name": "Alias"
        },
        { "jsonPath": "$.items[*].spec.workload.type", "language": "jsonata", "name": "Workload" },
        {
         "jsonPath": "$.items[*].spec.schematic.cue.template",
         "language": "jsonpath",
         "name": "CUE"
        },
        {
         "jsonPath": "$.items[*].spec.($exists(status.customStatus) ? status.customStatus : '')",
         "language": "jsonata",
         "name": "CustomStatus"
        },
        {
         "jsonPath": "$.items[*].spec.($exists(status.healthPolicy) ? status.healthPolicy : '')",
         "language": "jsonata",
         "name": "HealthPolicy"
        }
       ],
       "method": "GET",
       "urlPath": "/apis/core.oam.dev/v1beta1/componentdefinitions"
      }
     ]
    },
    {
     "title": "TraitDefinitions",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.items[*].metadata.name", "name": "Name" },
        { "jsonPath": "$.items[*].metadata.namespace", "language": "jsonpath", "name": "Namespace" },
        {
         "jsonPath": "$.items[*].metadata.annotations.\"definition.oam.dev/description\"",
         "language": "jsonata",
         "name": "Description"
        },
        {
         "jsonPath": "$.items[*].spec.schematic.cue.template",
         "language": "jsonpath",
         "name": "CUE"
        },
        {
         "jsonPath": "$.items[*].spec.($exists(status.customStatus) ? status.customStatus : '')",
         "language": "jsonata",
         "name": "CustomStatus"
        },
        {
         "jsonPath": "$.items[*].spec.($exists(status.healthPolicy) ? status.healthPolicy : '')",
         "language": "jsonata",
         "name": "HealthPolicy"
        }
       ],
       "method": "GET",
       "urlPath": "/apis/core.oam.dev/v1beta1/traitdefinitions"
      }
     ]
    },
    {
     "title": "WorkflowStepDefinitions",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.items[*].metadata.name", "name": "Name" },
        { "jsonPath": "$.items[*].metadata.namespace", "language": "jsonpath", "name": "Namespace" },
        {
         "jsonPath": "$.items[*].metadata.annotations.\"definition.oam.dev/description\"",
         "language": "jsonata",
         "name": "Description"
        },
        {
         "jsonPath": "$.items[*].spec.schematic.cue.template",
         "language": "jsonpath",
         "name": "CUE"
        }
       ],
       "method": "GET",
       "urlPath": "/apis/core.oam.dev/v1beta1/traitdefinitions"
      }
     ]
    }
   ]
  },
  {
   "title": "Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Addons",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 38 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        {
         "jsonPath": "$.items[*].metadata.labels.\"addons.oam.dev/name\"",
         "language": "jsonata",
         "name": "Name"
        },
        {
         "jsonPath": "$.items[*].metadata.labels.\"addons.oam.dev/version\"",
         "language": "jsonata",
         "name": "Version"
        },
        {
         "jsonPath": "$.items[*].metadata.labels.\"addons.oam.dev/registry\"",
         "language": "jsonata",
         "name": "Registry"
        },
        {
         "jsonPath": "$.items[*].($exists(status.status) ? status.status : '')",
         "language": "jsonata",
         "name": "Status"
        }
       ],
       "method": "GET",
       "urlPath": "/apis/core.oam.dev/v1beta1/applications?labelSelector=addons.oam.dev%2Fname"
      }
     ]
    },
    {
     "title": "Applications",
     "type": "table",
     "gridPos": { "h": 8, "w": 17, "x": 7, "y": 38 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.items[*].metadata.namespace", "name": "Namespace" },
        { "jsonPath": "$.items[*].metadata.name", "language": "jsonpath", "name": "Name" },
        {
         "jsonPath": "$.items[*].metadata.creationTimestamp",
         "language": "jsonpath",
         "name": "CreateTime"
        },
        {
         "jsonPath": "$.items[*].spec.($count(components))",
         "language": "jsonata",
         "name": "#Components"
        },
        {
         "jsonPath": "$.items[*].spec.($count(policies))",
         "language": "jsonata",
         "name": "#Traits"
        },
        {
         "jsonPath": "$.items[*].status.workflow.mode",
         "language": "jsonata",
         "name": "WorkflowMode"
        },
        {
         "jsonPath": "$.items[*].status.workflow.($count(steps))",
         "language": "jsonata",
         "name": "#WorkflowSteps"
        },
        { "jsonPath": "$.items[*].status.status", "language": "jsonpath", "name": "Status" },
        { "jsonPath": "$.items[*]", "language": "jsonpath", "name": "Json" }
       ],
       "method": "GET",
       "urlPath": "/apis/core.oam.dev/v1beta1/applications"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "KubeVela Applications",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "application",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Basic Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.metadata.name", "language": "jsonata" }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.metadata.namespace", "language": "jsonata" }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$millis() - $toMillis($.metadata.creationTimestamp)",
       "language": "jsonata",
       "name": "CreateTime"
      }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  {
   "title": "PublishVersion",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$exists($.metadata.annotations.\"app.oam.dev/publishVersion\") ? $.metadata.annotations.\"app.oam.dev/publishVersion\" : 'NA'",
       "language": "jsonata",
       "name": "CreateTime"
      }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  {
   "title": "Addon",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$exists($.metadata.labels.\"addons.oam.dev/name\")",
       "language": "jsonata",
       "name": "CreateTime"
      }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.status.status", "language": "jsonata", "name": "CreateTime" }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  {
   "title": "Components",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.spec.components[*].name", "name": "Name" },
      { "jsonPath": "$.spec.components[*].type", "language": "jsonpath", "name": "Type" },
      {
       "jsonPath": "$.spec.components[*].($exists(properties) ? $string(properties) : '{}')",
       "language": "jsonata",
       "name": "Properties"
      }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 4 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.spec.policies[*].name", "name": "Name" },
      { "jsonPath": "$.spec.policies[*].type", "language": "jsonpath", "name": "Type" },
      {
       "jsonPath": "$.spec.policies[*].($exists(properties) ? $string(properties) : '{}')",
       "language": "jsonata",
       "name": "Properties"
      }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  {
   "title": "WorkflowSteps",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 4 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.spec.workflow.steps[*].name", "name": "Name" },
      { "jsonPath": "$.spec.workflow.steps[*].type", "language": "jsonpath", "name": "Type" },
      {
       "jsonPath": "$.spec.workflow.steps[*].($exists(properties) ? $string(properties) : '{}')",
       "language": "jsonata",
       "name": "Properties"
      }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  {
   "title": "WorkflowStep Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 4 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.status.workflow.steps[*].id" },
      {
       "jsonPath": "$.status.workflow.steps[*].name",
       "language": "jsonpath",
       "name": ""
      },
      {
       "jsonPath": "$.status.workflow.steps[*].type",
       "language": "jsonpath",
       "name": ""
      },
      {
       "jsonPath": "$.status.workflow.steps[*].firstExecuteTime",
       "language": "jsonpath",
       "name": ""
      },
      {
       "jsonPath": "$.status.workflow.steps[*].lastExecuteTime",
       "language": "jsonpath",
       "name": ""
      },
      {
       "jsonPath": "$.status.workflow.steps[*].phase",
       "language": "jsonpath",
       "name": ""
      }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  { "title": "Related Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Managed Resources",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.status.appliedResources[*].(cluster ? cluster : 'local')",
       "language": "jsonata",
       "name": "Cluster"
      },
      {
       "jsonPath": "$.status.appliedResources[*].(namespace ? namespace : '-')",
       "language": "jsonata",
       "name": "Namespace"
      },
      {
       "jsonPath": "$.status.appliedResources[*].apiVersion",
       "language": "jsonata",
       "name": "APIVersion"
      },
      {
       "jsonPath": "$.status.appliedResources[*].kind",
       "language": "jsonata",
       "name": "Kind"
      },
      {
       "jsonPath": "$.status.appliedResources[*].name",
       "language": "jsonata",
       "name": "Name"
      },
      {
       "jsonPath": "$.status.appliedResources[*].(kind = 'Deployment' ? 'Detail' : '')",
       "language": "jsonata",
       "name": "Dashboard"
      },
      {
       "jsonPath": "$.status.appliedResources[*].('var-cluster=' & (cluster ? cluster : 'local') & '&var-namespace=' & (namespace ? namespace : '-') & '&var-name=' & name)",
       "language": "jsonata",
       "name": "URLParams"
      }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications/$application"
    }
   ]
  },
  {
   "title": "ResourceTrackers",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.items[*].metadata.name", "language": "jsonpath", "name": "Name" },
      { "jsonPath": "$.items[*].spec.type", "language": "jsonpath", "name": "Type" },
      {
       "jsonPath": "$.items[*].spec.applicationGeneration",
       "language": "jsonpath",
       "name": "Application Generation"
      },
      {
       "jsonPath": "$.items[*].spec.($count(managedResources))",
       "language": "jsonata",
       "name": "#Resources"
      },
      { "jsonPath": "$.items[*]", "language": "jsonpath", "name": "Json" }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/resourcetrackers?labelSelector=app.oam.dev%2Fname%3D$application,app.oam.dev%2Fnamespace%3D$namespace"
    }
   ]
  },
  {
   "title": "ApplicationRevisions",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.items[*].metadata.name", "language": "jsonpath", "name": "Name" },
      {
       "jsonPath": "$.items[*].metadata.creationTimestamp",
       "language": "jsonpath",
       "name": "CreateTime"
      },
      { "jsonPath": "$.items[*].status.succeeded", "language": "jsonpath", "name": "Succeeded" },
      { "jsonPath": "$.items[*]", "language": "jsonpath", "name": "Json" }
     ],
     "method": "GET",
     "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applicationrevisions?labelSelector=app.oam.dev%2Fname%3D$application"
    }
   ]
  },
  {
   "title": "Namespace($namespace) Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Overview",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$.items[*].metadata.namespace", "language": "jsonata", "name": "Namespace" },
        { "jsonPath": "$.items[*].metadata.name", "language": "jsonata", "name": "Name" },
        {
         "jsonPath": "$.items[*].metadata.creationTimestamp",
         "language": "jsonpath",
         "name": "CreateTime"
        },
        {
         "jsonPath": "$.items[*].spec.($count(components))",
         "language": "jsonata",
         "name": "#Components"
        },
        {
         "jsonPath": "$.items[*].spec.($count(policies))",
         "language": "jsonata",
         "name": "#Policies"
        },
        {
         "jsonPath": "$.items[*].status.workflow.mode",
         "language": "jsonata",
         "name": "WorkflowMode"
        },
        {
         "jsonPath": "$.items[*].status.workflow.($count(steps))",
         "language": "jsonata",
         "name": "#WorkflowSteps"
        },
        { "jsonPath": "$.items[*].status.status", "language": "jsonata", "name": "Status" },
        { "jsonPath": "$.items[*]", "language": "jsonpath", "name": "Json" }
       ],
       "method": "GET",
       "urlPath": "/apis/core.oam.dev/v1beta1/namespaces/$namespace/applications"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes Deployment",
 "description": "Kubernetes Deployments Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation, namespace)"
    }
   },
   {
    "name": "name",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation{namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "rate_interval",
    "query": "3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(container_memory_working_set_bytes,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\"}) by (uid, pod, pod_ip, host_ip, node)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"$name\",namespace=\"$namespace\",cluster=\"$cluster\"}) without (instance, pod)",
     "legendFormat": "Current"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$name\",namespace=\"$namespace\",cluster=\"$cluster\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"$name\",namespace=\"$namespace\",cluster=\"$cluster\"}) without (instance, pod)",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{cluster=\"$cluster\",deployment=\"$name\",namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{cluster=\"$cluster\",deployment=\"$name\",namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_metadata_generation{cluster=\"$cluster\",deployment=\"$name\",namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Ready Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{cluster=\"$cluster\",deployment=\"$name\",namespace=\"$namespace\"}"
    },
    {}
   ]
  },
  {
   "title": "Updated Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_updated{cluster=\"$cluster\",deployment=\"$name\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{cluster=\"$cluster\",deployment=\"$name\",namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"}) / sum(container_spec_memory_limit_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"}[$rate_interval])) / sum(container_spec_cpu_quota{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"}/100000)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"}[$rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"}[$rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"}/100000)"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",job=\"$job\"}[$rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",job=\"$job\"}[$rate_interval]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Network IO (Packets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "-sum(rate(container_network_transmit_packets_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",job=\"$job\"}[$rate_interval]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",job=\"$job\"}[$rate_interval]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "FileSystem IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",job=\"$job\"}[$rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(container_fs_write_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",job=\"$job\"}[$rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_processes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_sockets{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_threads{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time() - container_start_time_seconds{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\"${name}-[0-9a-z]+-[0-9a-z]+\",container!=\"\",job=\"$job\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}