apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: o11n-system
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-operator
