apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: o11n-system
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: ksm
spec:
  selector:
    matchLabels:      
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/instance: ksm
  replicas: 1
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: kube-state-metrics
        app.kubernetes.io/instance: ksm
    spec:
      hostNetwork: false
      serviceAccountName: kube-state-metrics
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsUser: 65534
      containers:
      - name: kube-state-metrics
        imagePullPolicy: IfNotPresent
        image: bitnami/kube-state-metrics:2.4.2
        ports:
          - containerPort: 8080
            name: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
