apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: o11n-system:prometheus-server
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-server
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "nodes/metrics", "services", "endpoints", "pods", "ingresses", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses/status", "ingresses"]
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["prometheus-server"]
    verbs: ["get"]