name: prometheus-operator
version: v0.1.0
description: TODO
icon: https://artifacthub.io/image/0503add5-3fce-4b63-bbf3-b9f649512a86@1x
url: https://prometheus.io/

tags:
 - observability
 - kubernetes
 - prometheus

deployTo:
  control_plane: true
  runtime_cluster: true

# needNamespace:
#   - o11n-system

invisible: false
